spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/projm2
spring.datasource.username=luis
spring.datasource.password=luis123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
